// LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// USER LOADING
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

// REGISTER
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// CATEGORY
export const CATEGORY_LOADING_REQUEST = "CATEGORY_LOADING_REQUEST";
export const CATEGORY_LOADING_SUCCESS = "CATEGORY_LOADING_SUCCESS";
export const CATEGORY_LOADING_FAILURE = "CATEGORY_LOADING_FAILURE";

// PRODUCT
export const PRODUCT_LOADING_REQUEST = "PRODUCT_LOADING_REQUEST";
export const PRODUCT_LOADING_SUCCESS = "PRODUCT_LOADING_SUCCESS";
export const PRODUCT_LOADING_FAILURE = "PRODUCT_LOADING_FAILURE";

export const PRODUCT_SEARCH_REQUEST = "PRODUCT_SEARCH_REQUEST";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
export const PRODUCT_SEARCH_FAILURE = "PRODUCT_SEARCH_FAILURE";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAILURE = "PRODUCT_DETAIL_FAILURE";

// NOTIFY
export const GET_NOTIFY_REQUEST = "GET_NOTIFY_REQUEST";
export const GET_NOTIFY_SUCCESS = "GET_NOTIFY_SUCCESS";
export const GET_NOTIFY_FAILURE = "GET_NOTIFY_FAILURE";

export const READ_NOTIFY_REQUEST = "READ_NOTIFY_REQUEST";
export const READ_NOTIFY_SUCCESS = "READ_NOTIFY_SUCCESS";
export const READ_NOTIFY_FAILURE = "READ_NOTIFY_FAILURE";

export const REMOVE_NOTIFY_REQUEST = "REMOVE_NOTIFY_REQUEST";
export const REMOVE_NOTIFY_SUCCESS = "REMOVE_NOTIFY_SUCCESS";
export const REMOVE_NOTIFY_FAILURE = "REMOVE_NOTIFY_FAILURE";

export const SET_NOTIFY_REQUEST = "SET_NOTIFY_REQUEST";
export const SET_NOTIFY_SUCCESS = "SET_NOTIFY_SUCCESS";
export const SET_NOTIFY_FAILURE = "SET_NOTIFY_FAILURE";
